"use client";

import { Message, SituationState } from "@/lib/schema";
import { cleanFacts } from "@/lib/utils";

type Props = {
    conversation: Message[];
    situationState: SituationState | null;
    incidentNumber: number | null;
};

export default function DispatcherActionPanel({ conversation, situationState, incidentNumber }: Props) {
    function generateReport() {
        if (!situationState) return;

        const idLabel = incidentNumber ?? "----";
        const condition = cleanFacts(situationState.victim.condition).join(", ") || "Unknown";
        const medicalHistory = cleanFacts(situationState.knownFacts.medicalHistory).join(", ") || "None reported";

        const win = window.open("", "_blank");
        if (!win) return;

        win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Incident Report #${idLabel}</title>
          <style>
            body {
              font-family: 'Courier New', monospace;
              background: #0a0c0e;
              color: #e6e8eb;
              padding: 40px;
              max-width: 700px;
              margin: 0 auto;
              line-height: 1.6;
            }
            h1 {
              font-size: 20px;
              border-bottom: 2px solid #3ddc97;
              padding-bottom: 10px;
              margin-bottom: 20px;
              letter-spacing: 1px;
            }
            .meta { color: #7a828e; font-size: 13px; margin-bottom: 20px; }
            .meta span { color: #e6e8eb; font-weight: bold; }
            .priority {
              display: inline-block;
              padding: 4px 12px;
              border-radius: 4px;
              font-weight: bold;
              background: #f2914b22;
              border: 1px solid #f2914b;
              color: #f2914b;
            }
            section { margin-bottom: 24px; }
            h2 {
              font-size: 12px;
              text-transform: uppercase;
              letter-spacing: 1.5px;
              color: #7a828e;
              margin-bottom: 8px;
            }
            p { margin: 4px 0; font-size: 14px; }
            ul { margin: 4px 0; padding-left: 20px; font-size: 14px; }
            .transcript-line { font-size: 12px; color: #b0b6bd; margin: 3px 0; }
            .footer { margin-top: 30px; font-size: 11px; color: #555; border-top: 1px solid #232830; padding-top: 12px; }
            .print-btn {
              background: #1d4ed8; color: white; border: none; padding: 10px 18px;
              border-radius: 6px; font-family: inherit; cursor: pointer; margin-bottom: 24px;
            }
            @media print { .print-btn { display: none; } }
          </style>
        </head>
        <body>
          <button class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</button>

          <h1>🚨 EMERGENCYIQ — INCIDENT REPORT</h1>
          <div class="meta">
            Incident ID: <span>#${idLabel}</span> &nbsp;|&nbsp;
            Generated: <span>${new Date().toLocaleString()}</span>
          </div>

          <section>
            <h2>Priority</h2>
            <span class="priority">${situationState.severity.toUpperCase()} — ${situationState.severityScore}/100</span>
            <p style="margin-top:8px; color:#b0b6bd;">${situationState.severityReason}</p>
          </section>

          <section>
            <h2>Incident Type</h2>
            <p>${situationState.incidentType}</p>
          </section>

          <section>
            <h2>Victim</h2>
            <p>${situationState.victim.role}${situationState.victim.age ? ", age " + situationState.victim.age : ""}</p>
            <p>Condition: ${condition}</p>
            <p>Medical history: ${medicalHistory}</p>
          </section>

          <section>
            <h2>Critical Unknowns</h2>
            <ul>
              ${situationState.criticalUnknowns.map((u) => `<li>${u}</li>`).join("")}
            </ul>
          </section>

          <section>
            <h2>Recommended Response</h2>
            <ul>
              ${situationState.recommendedResources.map((r) => `<li>${r}</li>`).join("")}
            </ul>
            <p style="color:#e5484d; font-weight:bold; margin-top:6px;">Dispatch Priority: ${situationState.dispatchPriority}</p>
          </section>

          <section>
            <h2>Call Transcript</h2>
            ${conversation.map((m) => `<p class="transcript-line">[${m.timestamp}] ${m.speaker.toUpperCase()}: "${m.text}"</p>`).join("")}
          </section>

          <div class="footer">Generated by EmergencyIQ — Emergency Situation Intelligence Platform</div>
        </body>
      </html>
    `);
        win.document.close();
    }

    return (
        <div className="eiq-card p-5">
            <h2 className="eiq-section-label mb-4">⚡ Dispatcher Actions</h2>
            <div className="space-y-2.5">
                {/* Primary CTA */}
                <button
                    onClick={generateReport}
                    disabled={!situationState}
                    className="w-full eiq-btn-primary px-4 py-3 text-sm"
                >
                    📄 Generate Incident Report
                </button>

                {/* Disabled — Coming Soon */}
                <div className="relative group">
                    <button
                        disabled
                        className="w-full eiq-btn-disabled-pretty px-4 py-3 text-sm flex items-center justify-center gap-2"
                    >
                        🔔 Notify Responders
                        <span className="text-[9px] uppercase tracking-wider bg-[var(--eiq-border)] text-[var(--eiq-muted)] px-1.5 py-0.5 rounded">
                            Coming Soon
                        </span>
                    </button>
                    <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-1.5 bg-[var(--eiq-surface-hover)] border border-[var(--eiq-border)] rounded-lg text-xs text-[var(--eiq-text-secondary)] opacity-0 group-hover:opacity-100 transition-opacity duration-200 pointer-events-none whitespace-nowrap z-20">
                        Requires CAD Integration
                    </div>
                </div>

                <div className="relative group">
                    <button
                        disabled
                        className="w-full eiq-btn-disabled-pretty px-4 py-3 text-sm flex items-center justify-center gap-2"
                    >
                        📤 Export Summary
                        <span className="text-[9px] uppercase tracking-wider bg-[var(--eiq-border)] text-[var(--eiq-muted)] px-1.5 py-0.5 rounded">
                            Coming Soon
                        </span>
                    </button>
                    <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-1.5 bg-[var(--eiq-surface-hover)] border border-[var(--eiq-border)] rounded-lg text-xs text-[var(--eiq-text-secondary)] opacity-0 group-hover:opacity-100 transition-opacity duration-200 pointer-events-none whitespace-nowrap z-20">
                        Requires CAD Integration
                    </div>
                </div>
            </div>
        </div>
    );
}